
# CREATE  A FILE 

# with open("abdul.txt", "x") as f:
#     f.write("hi how are you")




# CHECK THE FILE PATH
# import os
# print(os.getcwd())





# REPLACE THE WORD

# with open("D:\ assign 1.txt", "r") as f:
#     data = f.read()

# with open("D:\ assign 1.txt", "w") as f:
#     f.write(data.replace("java", "python"))




# FIND THE WORD 

# def check_work():
#     with open("D:\ assign 1.txt" ,"r") as f:
#         data=f.read()
#     user=input("Enter the word to find = ")
#     if (data.find(user) != -1):
#         print("found")
#     else:
#         print("Not found")
# check_work()



#  READ THE FILE
# with open("D:\ assign 1.txt", "r")as f:
#     data=f.read()
#     print(data)


# REMOVE THE FILE

# import os
# os.remove("D:\ assign 1.txt")
